<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dhara.AI.Inference\Dhara.AI.Inference.csproj" />
  </ItemGroup>

  <Import Project="build\Dhara.AI.LocalEmbeddings.targets" Condition="Exists('build\Dhara.AI.LocalEmbeddings.targets')" />

</Project>
